//our root layout - got our metadata instead of using head element we use metadata export with title and description 
import '../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nextjs practice', //changes tab 
  description: 'Generated by create next app',
}
//root layout - our HTML page - our DOM that gets rendered to the rest of the application to get rendered into 
//rename page2.tsx to page.tsx under app and now conflict, go back to index.tsx under pages which we are migrating from and grab link out of there 
//don't need <head> anymore in pages/index.tsx because it is already handled by the metadata

//functional component and return 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    
    </html>
  )
}
